[package]
name = "g85_contacts_web_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
diesel = { version = "2.2.0", features = ["postgres","r2d2", "chrono"] }
dotenvy = "0.15"
log = "0.4.19"